# Generated by Django 4.1.7 on 2023-03-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shaxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasmla/')),
                ('ism_familya', models.CharField(max_length=200)),
                ('ishi', models.CharField(max_length=200)),
                ('instagrami', models.CharField(max_length=200)),
                ('telegrami', models.CharField(max_length=200)),
                ('facebooki', models.CharField(max_length=200)),
            ],
        ),
    ]
